import '../globals.css';
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Oru phones',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en bg-gray-100">
      <body className={inter.className}>
      
        <Navbar />
        {children}
        
        </body>
    </html>
  )
}
